INSERT INTO Messages (
	Id,
	RoomId,
	SenderId,
	MessageText,
	TimeStamp,
	IsEdited,
	EditedAt,
	IsDeleted,
	DeletedAt
  )
VALUES (
	Id:integer,
	RoomId:integer,
	SenderId:integer,
	'MessageText:text',
	'TimeStamp:timestamp with time zone',
	IsEdited:boolean,
	'EditedAt:timestamp with time zone',
	IsDeleted:boolean,
	'DeletedAt:timestamp with time zone'
  );CREATE TABLE public."Messages" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE START 1) NOT NULL,
	"RoomId" int4 NOT NULL,
	"SenderId" int4 NOT NULL,
	"MessageText" text NOT NULL,
	"TimeStamp" timestamptz NOT NULL,
	"IsEdited" bool NOT NULL,
	"EditedAt" timestamptz NULL,
	"IsDeleted" bool NOT NULL,
	"DeletedAt" timestamptz NULL,
	CONSTRAINT "PK_Messages" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Messages_Chatrooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Chatrooms"("Id") ON DELETE CASCADE,
	CONSTRAINT "FK_Messages_Users_SenderId" FOREIGN KEY ("SenderId") REFERENCES "Users"("UserId") ON DELETE CASCADE
)